export const usersData = [
  {
    id: "u1",
    name: "Mona Khaled",
    displayName: "Mona K.",
    userCode: "USR-1001",
    email: "mona@example.com",
    phone: "+20 101 234 5678",
    location: "Cairo",
    password: "mona1234",
    image: "",
  },
  {
    id: "u2",
    name: "Ahmed Tarek",
    displayName: "Ahmed T.",
    userCode: "USR-1002",
    email: "ahmed@example.com",
    phone: "+20 109 876 5432",
    location: "Alexandria",
    password: "ahmed1234",
    image: "",
  },
  {
    id: "u3",
    name: "Sara Mohamed",
    displayName: "Sara M.",
    userCode: "USR-1003",
    email: "sara@example.com",
    phone: "+20 111 111 1111",
    location: "Giza",
    password: "sara1234",
    image: "",
  },
];

export const doctorsData = [
  {
    id: "d1",
    name: "Dr. Sarah Ahmed",
    email: "dr.sarah@example.com",
    position: "Senior Consultant",
    specialization: "Clinical Psychology",
    yearsOfExperience: 9,
    rating: 4.9,
    reviewsNumber: 48,
    about: "Experienced therapist helping patients with anxiety and depression.",
    therapyApproach: "CBT and supportive psychotherapy.",
    certificates: "Board Certified, Trauma-Informed Care",
    clientReviews: "Very kind, highly professional, excellent communication",
    availableSlots: "Sun 10:00, Tue 14:00, Thu 09:00",
    password: "doctor123",
    status: "Active",
    image: "",
  },
  {
    id: "d2",
    name: "Dr. Omar Hassan",
    email: "dr.omar@example.com",
    position: "Consultant",
    specialization: "Psychiatry",
    yearsOfExperience: 12,
    rating: 4.7,
    reviewsNumber: 34,
    about: "Focused on evidence-based psychiatric treatment and follow-up.",
    therapyApproach: "Medication management and integrated counseling.",
    certificates: "Psychiatry Board, Mental Health Diploma",
    clientReviews: "Great listener, clear plans",
    availableSlots: "Mon 11:00, Wed 16:00",
    password: "doctor123",
    status: "Inactive",
    image: "",
  },
];

